
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 21 15:53:15 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 5;
  public static final int CASE = 21;
  public static final int LPAREN = 12;
  public static final int SEMI = 7;
  public static final int CONTINUE = 23;
  public static final int RPAREN = 13;
  public static final int AND = 16;
  public static final int LS = 36;
  public static final int CHAR_C = 49;
  public static final int BOOL_C = 48;
  public static final int OR = 17;
  public static final int COMMA = 8;
  public static final int CLASS = 43;
  public static final int LSE = 37;
  public static final int INC = 27;
  public static final int DIV = 40;
  public static final int PLUS = 38;
  public static final int ASSIGN = 6;
  public static final int IF = 14;
  public static final int BGE = 35;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int EQUAL = 32;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int MUL = 41;
  public static final int MOD = 42;
  public static final int IDENT = 50;
  public static final int BREAK = 22;
  public static final int VOID = 44;
  public static final int SWITCH = 20;
  public static final int LBRACK = 9;
  public static final int COLON = 45;
  public static final int BG = 34;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int READ = 25;
  public static final int RBRACK = 10;
  public static final int WHILE = 19;
  public static final int DEFAULT = 46;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 11;
  public static final int PROG = 2;
  public static final int DIFF = 33;
  public static final int DEC = 28;
  public static final int TERN = 29;
  public static final int NUM_C = 47;
  public static final int SUB = 39;
  public static final int PRINT = 26;
  public static final int DO = 18;
}

